### PR TITLE
Sync'ed with codefunc:master, resolved conflicts. Ready to merge automatically.

### PR DESCRIPTION
**Pull request by d-m-h**

### CODE REVIEW

**Comment by codefunc** [comment]
Thanks it's merged; much appreciated.

**Comment by codefunc** [comment]
I'm also look at reduce all of this:
`<div class="CPlusPlus" style="display: none;">
  <table width="100%">
    <tr style="border: none; padding: 0">
      <td style="border: none; padding: 0;"><h5>C++</h5></td>
    </tr>
  </table>`

...and this... `  <table width="100%">
    <tr style="border: none; padding: 0">
      <td style="border: none; padding: 0;"><h5>C++ OUTPUT</h5></td>
    </tr>
  </table>
  <div class="codefunc-result">45</div>
</div>`

To two div tags e.g. `<div  class="CPlusPlus"/>` and try to generate the rest.

**Comment by d-m-h** [comment]
May I suggest the use of identifiers to make life easier?

**Comment by d-m-h** [comment]
Curious. How will you resolve such discrepancies when attempting to explain the reduce/fold functionality?

```C#
TSource folded = enumerator.Current;
while (enumerator.MoveNext ())
  folded = func (folded, enumerator.Current);
return folded;
```

```Python
    for element in it:
        value = function(value, element)
    return value
```

**Pull request merged**
