### PR TITLE
Altered languages first page with list of languages. Added C++ snippets to 2nd page.

### PR DESCRIPTION
**Pull request by d-m-h**
Modified Functional-Programming.md to include the full list of languages.

Modified What-is-Functional-Programming?.md to include C++ snippets.

### CODE REVIEW

**Comment by codefunc** [comment]
Can you please catch up your fork re "This branch is 3 commits ahead, 8 commits behind codefunc:master.". Difficult to commit.

**Comment by d-m-h** [comment]
Sure, I'll do that now.

Re: Tags. I'm not sure what tags you're referring to specifically.

**Comment by codefunc** [comment]
If you look here: https://github.com/codefunc/codefunc.github.io/blob/master/_layouts/post.html#L21; you'll see I moved all the languages to the post.html; I'll add C++ to this

I'm also removing all these tags:
`<div align="right">
<b>Preferred Language:</b>&nbsp;
<select onchange="choose_language(
      this.options[this.selectedIndex].getAttribute('value'), 
      ['CSharp', 'Java', 'JavaScript', 'PHP', 'Python', 'Swift']);">
  <option value="1" selected>C#</option>
  <option value="2">Java</option>
  <option value="3">JavaScript</option>
  <option value="4">PHP</option>
  <option value="5">Python</option>
  <option value="6">Swift</option>
</select>
</div>`
They get dynamically built based on the content detect for the post.

**Comment by d-m-h** [comment]
Gotcha. Right, my repo will merge automatically with yours. (I hope)

**Pull request closed without merging**
